export const UPDATE_TOPLIST_OFFICIAL = 'UPDATE_TOPLIST_OFFICIAL'  //更新官方榜单列表
export const UPDATE_TOPLIST_SELECTED = 'UPDATE_TOPLIST_SELECTED'  //更新精选榜单列表
export const UPDATE_TOPLIST_GENER = 'UPDATE_TOPLIST_GENER'  //更新曲风榜单列表
export const UPDATE_TOPLIST_LANGUAGE = 'UPDATE_TOPLIST_LANGUAGE'  //更新语言榜单列表